name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan my web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://cis.del.ac.id'
          fail_action: false 
